micronaut:
  application:
    name: micronaut_auth0
  security:
    authentication: idtoken
    oauth2:
      clients:
        auth0:
          client-id: '${OAUTH_CLIENT_ID:xxx}'
          client-secret: '${OAUTH_CLIENT_SECRET:xxx}'
          openid:
            issuer: '${OAUTH_CLIENT_DOMAIN:xxx}'
    endpoints:
      logout:
        get-allowed: true